//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP.WsEmisionTimbrado33 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/")]
    public partial class EmisionTimbradoException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeExceptionField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codeException {
            get {
                return this.codeExceptionField;
            }
            set {
                this.codeExceptionField = value;
                this.RaisePropertyChanged("codeException");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/")]
    public partial class wsResponseBO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] acuseField;
        
        private byte[][] arregloAcuseField;
        
        private string cadenaOriginalField;
        
        private string cadenaOriginalTimbreField;
        
        private int codigoErrorField;
        
        private System.DateTime fechaHoraTimbradoField;
        
        private bool fechaHoraTimbradoFieldSpecified;
        
        private string folioUDDIField;
        
        private bool isErrorField;
        
        private bool isErrorFieldSpecified;
        
        private string messageField;
        
        private byte[] pDFField;
        
        private string rutaDescargaPDFField;
        
        private string rutaDescargaXMLField;
        
        private string selloDigitalEmisorField;
        
        private string selloDigitalTimbreSATField;
        
        private byte[] xMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] acuse {
            get {
                return this.acuseField;
            }
            set {
                this.acuseField = value;
                this.RaisePropertyChanged("acuse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("arregloAcuse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=1)]
        public byte[][] arregloAcuse {
            get {
                return this.arregloAcuseField;
            }
            set {
                this.arregloAcuseField = value;
                this.RaisePropertyChanged("arregloAcuse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
                this.RaisePropertyChanged("cadenaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cadenaOriginalTimbre {
            get {
                return this.cadenaOriginalTimbreField;
            }
            set {
                this.cadenaOriginalTimbreField = value;
                this.RaisePropertyChanged("cadenaOriginalTimbre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("codigoError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaHoraTimbrado {
            get {
                return this.fechaHoraTimbradoField;
            }
            set {
                this.fechaHoraTimbradoField = value;
                this.RaisePropertyChanged("fechaHoraTimbrado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraTimbradoSpecified {
            get {
                return this.fechaHoraTimbradoFieldSpecified;
            }
            set {
                this.fechaHoraTimbradoFieldSpecified = value;
                this.RaisePropertyChanged("fechaHoraTimbradoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string folioUDDI {
            get {
                return this.folioUDDIField;
            }
            set {
                this.folioUDDIField = value;
                this.RaisePropertyChanged("folioUDDI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool isError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
                this.RaisePropertyChanged("isError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isErrorSpecified {
            get {
                return this.isErrorFieldSpecified;
            }
            set {
                this.isErrorFieldSpecified = value;
                this.RaisePropertyChanged("isErrorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
                this.RaisePropertyChanged("PDF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string rutaDescargaPDF {
            get {
                return this.rutaDescargaPDFField;
            }
            set {
                this.rutaDescargaPDFField = value;
                this.RaisePropertyChanged("rutaDescargaPDF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string rutaDescargaXML {
            get {
                return this.rutaDescargaXMLField;
            }
            set {
                this.rutaDescargaXMLField = value;
                this.RaisePropertyChanged("rutaDescargaXML");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string selloDigitalEmisor {
            get {
                return this.selloDigitalEmisorField;
            }
            set {
                this.selloDigitalEmisorField = value;
                this.RaisePropertyChanged("selloDigitalEmisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string selloDigitalTimbreSAT {
            get {
                return this.selloDigitalTimbreSATField;
            }
            set {
                this.selloDigitalTimbreSATField = value;
                this.RaisePropertyChanged("selloDigitalTimbreSAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=14)]
        public byte[] XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
                this.RaisePropertyChanged("XML");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", ConfigurationName="WsEmisionTimbrado33.WsEmisionTimbrado33")]
    public interface WsEmisionTimbrado33 {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/EmitirTimbrarRequest", ReplyAction="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/EmitirTimbrarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SAP.WsEmisionTimbrado33.EmisionTimbradoException), Action="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/EmitirTimbrar/Fault/Emi" +
            "sionTimbradoException", Name="EmisionTimbradoException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SAP.WsEmisionTimbrado33.EmitirTimbrarResponse EmitirTimbrar(SAP.WsEmisionTimbrado33.EmitirTimbrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/EmitirTimbrarRequest", ReplyAction="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/EmitirTimbrarResponse")]
        System.Threading.Tasks.Task<SAP.WsEmisionTimbrado33.EmitirTimbrarResponse> EmitirTimbrarAsync(SAP.WsEmisionTimbrado33.EmitirTimbrarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/CodigoConfirmacionReque" +
            "st", ReplyAction="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/CodigoConfirmacionRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SAP.WsEmisionTimbrado33.EmisionTimbradoException), Action="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/CodigoConfirmacion/Faul" +
            "t/EmisionTimbradoException", Name="EmisionTimbradoException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SAP.WsEmisionTimbrado33.CodigoConfirmacionResponse CodigoConfirmacion(SAP.WsEmisionTimbrado33.CodigoConfirmacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/CodigoConfirmacionReque" +
            "st", ReplyAction="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/CodigoConfirmacionRespo" +
            "nse")]
        System.Threading.Tasks.Task<SAP.WsEmisionTimbrado33.CodigoConfirmacionResponse> CodigoConfirmacionAsync(SAP.WsEmisionTimbrado33.CodigoConfirmacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmitirTimbrar", WrapperNamespace="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped=true)]
    public partial class EmitirTimbrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idServicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] xml;
        
        public EmitirTimbrarRequest() {
        }
        
        public EmitirTimbrarRequest(string usuario, string contrasenia, int idServicio, byte[] xml) {
            this.usuario = usuario;
            this.contrasenia = contrasenia;
            this.idServicio = idServicio;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmitirTimbrarResponse", WrapperNamespace="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped=true)]
    public partial class EmitirTimbrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SAP.WsEmisionTimbrado33.wsResponseBO @return;
        
        public EmitirTimbrarResponse() {
        }
        
        public EmitirTimbrarResponse(SAP.WsEmisionTimbrado33.wsResponseBO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CodigoConfirmacion", WrapperNamespace="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped=true)]
    public partial class CodigoConfirmacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idServicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] xml;
        
        public CodigoConfirmacionRequest() {
        }
        
        public CodigoConfirmacionRequest(string usuario, string contrasenia, int idServicio, byte[] xml) {
            this.usuario = usuario;
            this.contrasenia = contrasenia;
            this.idServicio = idServicio;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CodigoConfirmacionResponse", WrapperNamespace="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped=true)]
    public partial class CodigoConfirmacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CodigoConfirmacionResponse() {
        }
        
        public CodigoConfirmacionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsEmisionTimbrado33Channel : SAP.WsEmisionTimbrado33.WsEmisionTimbrado33, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsEmisionTimbrado33Client : System.ServiceModel.ClientBase<SAP.WsEmisionTimbrado33.WsEmisionTimbrado33>, SAP.WsEmisionTimbrado33.WsEmisionTimbrado33 {
        
        public WsEmisionTimbrado33Client() {
        }
        
        public WsEmisionTimbrado33Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsEmisionTimbrado33Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsEmisionTimbrado33Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsEmisionTimbrado33Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAP.WsEmisionTimbrado33.EmitirTimbrarResponse SAP.WsEmisionTimbrado33.WsEmisionTimbrado33.EmitirTimbrar(SAP.WsEmisionTimbrado33.EmitirTimbrarRequest request) {
            return base.Channel.EmitirTimbrar(request);
        }
        
        public SAP.WsEmisionTimbrado33.wsResponseBO EmitirTimbrar(string usuario, string contrasenia, int idServicio, byte[] xml) {
            SAP.WsEmisionTimbrado33.EmitirTimbrarRequest inValue = new SAP.WsEmisionTimbrado33.EmitirTimbrarRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            inValue.idServicio = idServicio;
            inValue.xml = xml;
            SAP.WsEmisionTimbrado33.EmitirTimbrarResponse retVal = ((SAP.WsEmisionTimbrado33.WsEmisionTimbrado33)(this)).EmitirTimbrar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAP.WsEmisionTimbrado33.EmitirTimbrarResponse> SAP.WsEmisionTimbrado33.WsEmisionTimbrado33.EmitirTimbrarAsync(SAP.WsEmisionTimbrado33.EmitirTimbrarRequest request) {
            return base.Channel.EmitirTimbrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAP.WsEmisionTimbrado33.EmitirTimbrarResponse> EmitirTimbrarAsync(string usuario, string contrasenia, int idServicio, byte[] xml) {
            SAP.WsEmisionTimbrado33.EmitirTimbrarRequest inValue = new SAP.WsEmisionTimbrado33.EmitirTimbrarRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            inValue.idServicio = idServicio;
            inValue.xml = xml;
            return ((SAP.WsEmisionTimbrado33.WsEmisionTimbrado33)(this)).EmitirTimbrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAP.WsEmisionTimbrado33.CodigoConfirmacionResponse SAP.WsEmisionTimbrado33.WsEmisionTimbrado33.CodigoConfirmacion(SAP.WsEmisionTimbrado33.CodigoConfirmacionRequest request) {
            return base.Channel.CodigoConfirmacion(request);
        }
        
        public string CodigoConfirmacion(string usuario, string contrasenia, int idServicio, byte[] xml) {
            SAP.WsEmisionTimbrado33.CodigoConfirmacionRequest inValue = new SAP.WsEmisionTimbrado33.CodigoConfirmacionRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            inValue.idServicio = idServicio;
            inValue.xml = xml;
            SAP.WsEmisionTimbrado33.CodigoConfirmacionResponse retVal = ((SAP.WsEmisionTimbrado33.WsEmisionTimbrado33)(this)).CodigoConfirmacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAP.WsEmisionTimbrado33.CodigoConfirmacionResponse> SAP.WsEmisionTimbrado33.WsEmisionTimbrado33.CodigoConfirmacionAsync(SAP.WsEmisionTimbrado33.CodigoConfirmacionRequest request) {
            return base.Channel.CodigoConfirmacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAP.WsEmisionTimbrado33.CodigoConfirmacionResponse> CodigoConfirmacionAsync(string usuario, string contrasenia, int idServicio, byte[] xml) {
            SAP.WsEmisionTimbrado33.CodigoConfirmacionRequest inValue = new SAP.WsEmisionTimbrado33.CodigoConfirmacionRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            inValue.idServicio = idServicio;
            inValue.xml = xml;
            return ((SAP.WsEmisionTimbrado33.WsEmisionTimbrado33)(this)).CodigoConfirmacionAsync(inValue);
        }
    }
}
